name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_ADDRESS: ${{ secrets.DOCKER_ADDRESS }}
          DOCKER_REPO_NAME: ${{secrets.DOCKER_REPO_NAME}}
        run: |
          sudo tee /etc/docker/daemon.json <<- EOF
            {
              "insecure-registries": [
                "$DOCKER_ADDRESS"
              ]
            }
          EOF
          sudo service docker restart
          docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD $DOCKER_ADDRESS
          docker build -t $DOCKER_ADDRESS/$DOCKER_REPO_NAME . && docker push $DOCKER_ADDRESS/$DOCKER_REPO_NAME
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_ADDRESS: ${{ secrets.DOCKER_ADDRESS }}
          TARGET_MACHINE: ${{ secrets.TARGET_MACHINE }}
          DOCKER_REPO_NAME: ${{secrets.DOCKER_REPO_NAME}}
        run: |
          sudo tee /etc/docker/daemon.json <<- EOF
                      {
                        "insecure-registries": [
                          "$DOCKER_ADDRESS"
                        ]
                      }
          EOF
          sudo service docker restart
          sudo tee /home/id_rsa <<- EOF
          $DEPLOY_KEY
          EOF
#          ssh-keygen -R $TARGET_MACHINE
          ssh -i /home/id_rsa $TARGET_MACHINE "docker rm -f neilwang.wiki"
          ssh -i /home/id_rsa $TARGET_MACHINE "docker pull $DOCKER_ADDRESS/neilwang.wiki:latest"
          ssh -i /home/id_rsa $TARGET_MACHINE "docker run --name neilwang.wiki -d -p 10080:80 --restart always $DOCKER_ADDRESS/$DOCKER_REPO_NAME"
