name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} {{secrets.DOCKER_ADDRESS}}
          sh ./scripts/build.sh
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: |
          tee /home/id_rsa <<-'EOF'
          {{secrets.DEPLOY_KEY}}
          EOF
          sh ./scripts/deploy.sh
